### ISSUE TITLE
REDIRECT_URI??

### ISSUE THREAD

**Issue by Juan-cc** [OfficeDev/O365-Android-Connect#21]
Hi,
I have a valid CLIENT_ID for my outlook 365 account, but I am just a simple user so I dont know what the REDIRECT_URI is. How can I complete that field?
 public static final String CLIENT_ID = "my id";
    public static final String REDIRECT_URI = "___";

Thanks!
Juan

**Comment by davechmsft** [comment]
Hi Juan,

The redirect URI is just an additional piece of verification data sent to authenticate your app. When you register your app in Azure, you specify the URI which can be any URI you want to use. Any valid URI string will work. The redirect URI will be on the "Configure" page for your app in the Azure management portal. 

BTW: You can also register apps at http://dev.office.com/app-registration which helps make the process a bit quicker and easier.

Also: This connect sample is using the older API. If you want to use the newer Microsoft Graph API for connecting to Office 365, see the repo: https://github.com/OfficeDev/O365-Android-Microsoft-Graph-Connect

Hope this helps,
David

**Comment by Juan-cc** [comment]
Thanks for your prompt reploy David!
The app registration http://dev.office.com/app-registration worked perfectly fine!

Thanks,
Juan

**Comment by Ricalo** [comment]
Thank you, @Juan-cc and @davechmsft. It seems like this issue is resolved, feel free to reopen if that's not the case.
[Office 365 app registration tool](http://dev.office.com/app-registration) FTW!
